Add bookings
ds111166/java-shareit pull request #2
Opened 2023-11-10 05:35 UTC by ds111166

2023-11-11 09:49 UTC, YazykovMikhail requested changes

2023-11-11 09:49 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +package ru.practicum.shareit.booking;
сделай папку сервис и репозиторий а то в одном месте навалено много классов

2023-11-11 09:49 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +package ru.practicum.shareit.booking;
касается всех сущностей

2023-11-11 09:49 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    private final UserMapper userMapper;
вообще так обычно не делается, каждый мапер отвечает только за свои обьекты. 
Т.е на вход в метод передаются уже все необходимые данные. 
Т.е эти мапперы должны быть в сервисе и ты в метод передаешь уже необходимые готовые обеькты

2023-11-11 09:49 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingDto createBooking(@RequestHeader("X-Sharer-User-Id") Long bookerId,
Назови лучше
BookingResponseDto
BookingRequestDto

если в нескольких запросах используется разные поля для у dto
например есть метод create а есть update, для метода create не нужно поле id, а для create нужно, тогда стоит сделать разыне dto
BookingCreateRequestDto
BookingUpdateRequestDto
у тебя в этом контроллере нет таких методов, но в других есть/будут поправь там. 
В dto не должно быт ьполей которые не используются в контракте для конкретного эндпоинта

2023-11-11 09:49 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    private final UserMapper userMapper;
либо в метод можно передавать конкретный user, не dto а именно модель и сетать конкретные поля
из user -> BookingDto.booker

2023-11-12 06:21 UTC, ds111166 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +package ru.practicum.shareit.booking;
**### ✔**

2023-11-12 06:40 UTC, ds111166 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingDto createBooking(@RequestHeader("X-Sharer-User-Id") Long bookerId,
_**✔**_

2023-11-12 12:40 UTC, ds111166 commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    private final UserMapper userMapper;
_**✔**_

2023-11-13 09:59 UTC, merged